version: "3"

services:
  gce-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./cloud-sql-admin.json:/config/key.json
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: >
      /cloud_sql_proxy
      -instances="${CLOUD_SQL_CONNECTION}"=tcp:0.0.0.0:${DB_PORT}
      -credential_file=/config/key.json

  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
